//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppApi.App_Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class MailBase_T
    {
        public long Id { get; set; }
        public Nullable<int> MailBoxId { get; set; }
        public byte[] MailData { get; set; }
        public Nullable<System.DateTime> RecDate { get; set; }
    }
}
