//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppApi.App_Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProviderAdd_T
    {
        public int Id { get; set; }
        public Nullable<int> PriId { get; set; }
        public string Name { get; set; }
        public Nullable<int> IsMain { get; set; }
        public string Sex { get; set; }
        public string Dept { get; set; }
        public string Job { get; set; }
        public string Email { get; set; }
        public string Tel { get; set; }
        public string Mobile { get; set; }
        public string QQ { get; set; }
        public string Wx { get; set; }
        public string Msn { get; set; }
        public string Skype { get; set; }
        public string Bak { get; set; }
        public string Creater { get; set; }
        public string CreaterName { get; set; }
        public Nullable<System.DateTime> CreateTm { get; set; }
        public string Updater { get; set; }
        public string UpdateName { get; set; }
        public Nullable<System.DateTime> UpdateTm { get; set; }
    }
}
