//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppApi.App_Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Circle_T
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public string Synopsis { get; set; }
        public string Creater { get; set; }
        public Nullable<System.DateTime> CreateTm { get; set; }
        public Nullable<int> Type { get; set; }
        public Nullable<int> IsAddCreater { get; set; }
        public byte[] HeadPortrait { get; set; }
        public Nullable<int> ParentId { get; set; }
        public Nullable<int> ReplyId { get; set; }
    }
}
