//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppApi.App_Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class InqOneAllInfo_V
    {
        public int Id { get; set; }
        public string No { get; set; }
        public Nullable<int> ClientId { get; set; }
        public Nullable<int> ChanceId { get; set; }
        public Nullable<int> PriId { get; set; }
        public string PriName { get; set; }
        public string PriLinkMan { get; set; }
        public string PriLinkPhone { get; set; }
        public string PriProNo { get; set; }
        public string PriProName { get; set; }
        public Nullable<int> ProId { get; set; }
        public string ProNo { get; set; }
        public string Currency { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<int> IsUpdate { get; set; }
        public Nullable<int> IsTax { get; set; }
        public Nullable<decimal> MOQPrice { get; set; }
        public Nullable<decimal> MOQ { get; set; }
        public Nullable<System.DateTime> InqDate { get; set; }
        public Nullable<System.DateTime> ValidDate { get; set; }
        public Nullable<int> SupplyDay { get; set; }
        public string Bak { get; set; }
        public string InqBak { get; set; }
        public string InqUserId { get; set; }
        public string InqUserName { get; set; }
        public string SpUserId { get; set; }
        public Nullable<int> Submit { get; set; }
        public Nullable<int> SpResult { get; set; }
        public string SpMsg { get; set; }
        public string SpUserName { get; set; }
        public Nullable<System.DateTime> SpTime { get; set; }
        public string Creater { get; set; }
        public string CreaterName { get; set; }
        public Nullable<System.DateTime> CreateTm { get; set; }
        public string Updater { get; set; }
        public string UpdaterName { get; set; }
        public Nullable<System.DateTime> UpdateTm { get; set; }
        public string ChanceNo { get; set; }
        public string UserName { get; set; }
        public string CnName { get; set; }
        public string EnName { get; set; }
        public string UserId { get; set; }
        public Nullable<int> InqLimitHour { get; set; }
        public Nullable<decimal> SuggestPrice { get; set; }
        public Nullable<int> IsUpdateSuggestPrice { get; set; }
        public Nullable<System.DateTime> InqLimit { get; set; }
        public string Port { get; set; }
        public Nullable<decimal> Num { get; set; }
        public string Packing { get; set; }
        public string Unit { get; set; }
        public string Brand { get; set; }
        public Nullable<int> Certificate { get; set; }
        public string Spec { get; set; }
        public Nullable<int> InquiryId { get; set; }
        public string LoadPort { get; set; }
        public string AimPort { get; set; }
        public string Transport { get; set; }
        public string ArkType { get; set; }
        public string QuoteBak { get; set; }
    }
}
