//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppApi.App_Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomsZcTj_T
    {
        public int Id { get; set; }
        public string BNo { get; set; }
        public Nullable<int> xunhao { get; set; }
        public string riqi { get; set; }
        public string jinchukou { get; set; }
        public string hsCode { get; set; }
        public string guojia { get; set; }
        public string guanqu { get; set; }
        public string yunshugongju { get; set; }
        public Nullable<decimal> jine { get; set; }
        public Nullable<long> liang { get; set; }
        public Nullable<decimal> junjia { get; set; }
        public string Creater { get; set; }
        public string CreaterName { get; set; }
        public Nullable<System.DateTime> CreateTm { get; set; }
    }
}
