//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppApi.App_Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Chance_V
    {
        public int Id { get; set; }
        public string No { get; set; }
        public string ChanceType { get; set; }
        public string Import { get; set; }
        public string UserName { get; set; }
        public string bak { get; set; }
        public string ChancePro { get; set; }
        public string Stage { get; set; }
        public string StageGraph { get; set; }
        public string State { get; set; }
        public string Inq { get; set; }
        public Nullable<int> MailCount { get; set; }
        public Nullable<int> ScheduleTm { get; set; }
        public string sumupid { get; set; }
        public Nullable<int> ClientId { get; set; }
        public Nullable<System.DateTime> EndTime { get; set; }
        public Nullable<System.DateTime> CreateTm { get; set; }
        public string ClientState { get; set; }
        public string Creater { get; set; }
        public string UserId { get; set; }
        public string LinkMan { get; set; }
        public string Email { get; set; }
        public Nullable<int> MailId { get; set; }
        public Nullable<System.DateTime> MailStart { get; set; }
        public Nullable<System.DateTime> MailNow { get; set; }
        public Nullable<System.DateTime> MailSendNow { get; set; }
        public Nullable<System.DateTime> MailRecNow { get; set; }
        public Nullable<System.DateTime> StockQuoteStart { get; set; }
        public Nullable<System.DateTime> StockQuoteEnd { get; set; }
        public Nullable<System.DateTime> QuoteStart { get; set; }
        public Nullable<System.DateTime> QuoteEnd { get; set; }
        public Nullable<System.DateTime> SampleStart { get; set; }
        public Nullable<System.DateTime> SampleEnd { get; set; }
        public Nullable<System.DateTime> SaleStart { get; set; }
        public Nullable<System.DateTime> SaleEnd { get; set; }
        public string SellNo { get; set; }
        public string CreaterName { get; set; }
        public string Updater { get; set; }
        public string UpdaterName { get; set; }
        public Nullable<System.DateTime> UpdateTm { get; set; }
        public string ClientName { get; set; }
        public Nullable<int> CommCount { get; set; }
        public string CommReadUID { get; set; }
        public string Country { get; set; }
        public string FollowBak { get; set; }
        public string Source { get; set; }
        public Nullable<int> IsOldClientInq { get; set; }
        public string ClientNo { get; set; }
        public Nullable<int> DeptId { get; set; }
        public Nullable<int> StateB { get; set; }
        public Nullable<System.DateTime> stime { get; set; }
        public Nullable<int> SubmitQ { get; set; }
        public Nullable<int> StateQ { get; set; }
        public Nullable<System.DateTime> SpTime { get; set; }
    }
}
