//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppApi.App_Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class clientpro_V
    {
        public Nullable<int> ProId { get; set; }
        public string No { get; set; }
        public string CnName { get; set; }
        public string EnName { get; set; }
        public string Spec { get; set; }
        public string BeUserName { get; set; }
        public string Currency { get; set; }
        public Nullable<decimal> CostPrice { get; set; }
        public Nullable<decimal> SellPrice { get; set; }
        public Nullable<int> ClientId { get; set; }
        public int Id { get; set; }
        public int ChanceProId { get; set; }
        public string myCostPrice { get; set; }
        public string myCurrency { get; set; }
        public string Num { get; set; }
        public string Inq { get; set; }
        public string InqLimit { get; set; }
        public string Bak { get; set; }
        public Nullable<System.DateTime> CreateTm { get; set; }
        public string CiqCode { get; set; }
        public string Unit { get; set; }
        public string CnBak { get; set; }
        public string EnBak { get; set; }
        public string Packing { get; set; }
    }
}
