//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppApi.App_Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ColumnSet_T
    {
        public int Id { get; set; }
        public string MenuNo { get; set; }
        public Nullable<int> Sort { get; set; }
        public string data_field { get; set; }
        public string data_title { get; set; }
        public string data_title_en { get; set; }
        public string data_sortName { get; set; }
        public string data_width { get; set; }
        public Nullable<bool> data_sortable { get; set; }
        public Nullable<bool> data_checkbox { get; set; }
        public Nullable<bool> data_radio { get; set; }
        public Nullable<bool> data_visible { get; set; }
        public string data_class { get; set; }
        public Nullable<int> data_rowspan { get; set; }
        public Nullable<int> data_colspan { get; set; }
        public string data_align { get; set; }
        public string data_halign { get; set; }
        public string data_falign { get; set; }
        public string data_valign { get; set; }
        public Nullable<bool> data_cardVisible { get; set; }
        public Nullable<bool> data_clickToSelect { get; set; }
        public string data_order { get; set; }
        public string data_titleTooltip { get; set; }
    }
}
