//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppApi.App_Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomsZc_T
    {
        public int Id { get; set; }
        public string BNo { get; set; }
        public string jinchukou { get; set; }
        public string bianma { get; set; }
        public string mingcheng { get; set; }
        public string yuedu { get; set; }
        public string qiyebianma { get; set; }
        public string qiyemingcheng { get; set; }
        public string shoufahuodi { get; set; }
        public Nullable<int> shuliang { get; set; }
        public Nullable<decimal> jine { get; set; }
        public Nullable<decimal> danjia { get; set; }
        public string yuanchanguo { get; set; }
        public string baoguankouan { get; set; }
        public string maoyifangshi { get; set; }
        public string yueshufangshi { get; set; }
        public string zhongzhuanguo { get; set; }
        public string shuliangdanwei { get; set; }
        public string dianhua { get; set; }
        public string chuanzhen { get; set; }
        public string youbian { get; set; }
        public string dianziyoujian { get; set; }
        public string lianxiren { get; set; }
        public string qiyexingzhi { get; set; }
        public string qiyedizhi { get; set; }
        public string shengfen { get; set; }
        public string nianfen { get; set; }
        public string Creater { get; set; }
        public string CreaterName { get; set; }
        public Nullable<System.DateTime> CreateTm { get; set; }
    }
}
