//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppApi.App_Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class DesktopOne_T
    {
        public int Id { get; set; }
        public string MenuNo { get; set; }
        public string Name { get; set; }
        public Nullable<int> Rank { get; set; }
        public Nullable<int> IsShow { get; set; }
        public string NumberName { get; set; }
        public string PercentageName { get; set; }
        public string Sql { get; set; }
        public string Creater { get; set; }
        public string CreaterName { get; set; }
        public Nullable<System.DateTime> CreateTm { get; set; }
    }
}
