//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppApi.App_Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class EdmTask_T
    {
        public int Id { get; set; }
        public Nullable<int> Mode { get; set; }
        public Nullable<int> MailBoxId { get; set; }
        public Nullable<int> Interval { get; set; }
        public string Subject { get; set; }
        public string FromName { get; set; }
        public string FromEmail { get; set; }
        public string FromDomain { get; set; }
        public string ReplyTo { get; set; }
        public string MailHtml { get; set; }
        public string Notify { get; set; }
        public string Track { get; set; }
        public string itTo { get; set; }
        public string AllGroup { get; set; }
        public string GroupName { get; set; }
        public string GroupNameNot { get; set; }
        public string UseSmtp { get; set; }
        public Nullable<int> Domain { get; set; }
        public Nullable<int> AD { get; set; }
        public Nullable<System.DateTime> PfTime { get; set; }
        public Nullable<System.DateTime> SendTime { get; set; }
        public string State { get; set; }
        public string Sp { get; set; }
        public string SpUserId { get; set; }
        public string SpUserName { get; set; }
        public Nullable<System.DateTime> SpTime { get; set; }
        public string SpBak { get; set; }
        public Nullable<int> MailCount { get; set; }
        public Nullable<int> SendCount { get; set; }
        public Nullable<int> WaitCount { get; set; }
        public Nullable<int> Success { get; set; }
        public Nullable<int> Failure { get; set; }
        public Nullable<int> OpenCount { get; set; }
        public Nullable<System.DateTime> EndTime { get; set; }
        public Nullable<int> ReTaskId { get; set; }
        public string Creater { get; set; }
        public string CreaterName { get; set; }
        public Nullable<System.DateTime> CreateTm { get; set; }
        public string Updater { get; set; }
        public string UpdaterName { get; set; }
        public Nullable<System.DateTime> UpdateTm { get; set; }
        public Nullable<System.DateTime> SubmitTime { get; set; }
        public Nullable<int> ApiReturnId { get; set; }
        public string TaskName { get; set; }
        public string RemoteURL { get; set; }
    }
}
