//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppApi.App_Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class FileAud_T
    {
        public long Id { get; set; }
        public Nullable<int> RootId { get; set; }
        public Nullable<long> FileId { get; set; }
        public string Name { get; set; }
        public string AudOp { get; set; }
        public Nullable<int> ToRootId { get; set; }
        public string Reason { get; set; }
        public string Creater { get; set; }
        public string CreaterName { get; set; }
        public Nullable<System.DateTime> CreateTm { get; set; }
        public Nullable<int> IsAud { get; set; }
        public Nullable<int> IsDone { get; set; }
        public Nullable<System.DateTime> AudTime { get; set; }
        public string AudUserId { get; set; }
        public string AudUserName { get; set; }
        public Nullable<System.DateTime> TimeOut { get; set; }
        public Nullable<int> OpenCount { get; set; }
        public Nullable<int> OpenCountNow { get; set; }
        public Nullable<int> OldRootId { get; set; }
        public string OldRootName { get; set; }
    }
}
