//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppApi.App_Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class File_T
    {
        public int Id { get; set; }
        public string TableName { get; set; }
        public Nullable<int> KeyId { get; set; }
        public string FileName { get; set; }
        public string FileType { get; set; }
        public Nullable<int> FileSize { get; set; }
        public string FileDb { get; set; }
        public Nullable<int> FileId { get; set; }
        public string DownloadID { get; set; }
        public string Creater { get; set; }
        public string CreaterName { get; set; }
        public Nullable<System.DateTime> CreateTm { get; set; }
        public Nullable<int> FileStoreId { get; set; }
        public string FileRoot { get; set; }
        public string FileKey { get; set; }
        public string FileStore { get; set; }
        public string FileZip { get; set; }
    }
}
