//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppApi.App_Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class FileTrash_T
    {
        public long Id { get; set; }
        public Nullable<int> RootId { get; set; }
        public string Code { get; set; }
        public string Type { get; set; }
        public string Name { get; set; }
        public string FileName { get; set; }
        public string FlashName { get; set; }
        public string FileRoot { get; set; }
        public Nullable<int> ServerId { get; set; }
        public string ConNo { get; set; }
        public string Bak { get; set; }
        public Nullable<long> FileSize { get; set; }
        public string FileType { get; set; }
        public string FileMimeType { get; set; }
        public string Creater { get; set; }
        public string CreaterName { get; set; }
        public Nullable<System.DateTime> CreateTm { get; set; }
        public string Updater { get; set; }
        public string UpdaterName { get; set; }
        public Nullable<System.DateTime> UpdateTm { get; set; }
        public Nullable<long> Sort { get; set; }
        public string IdenCode { get; set; }
        public Nullable<int> DeptId { get; set; }
        public string DeptName { get; set; }
        public Nullable<int> IsAud { get; set; }
        public string Security { get; set; }
        public string DelUserId { get; set; }
        public string DelUserName { get; set; }
        public Nullable<System.DateTime> DelTime { get; set; }
        public string TagClass { get; set; }
        public string Tag { get; set; }
        public string TagId { get; set; }
        public string PreviewPic1 { get; set; }
        public string PreviewPic2 { get; set; }
        public string FileStore { get; set; }
        public string FileZip { get; set; }
    }
}
