//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppApi.App_Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class MailClient_T
    {
        public int ClientMailId { get; set; }
        public string ClientEmail { get; set; }
        public Nullable<int> ClientId { get; set; }
        public Nullable<int> ClientAddId { get; set; }
        public string ClientInfo { get; set; }
        public string ClientAddInfo { get; set; }
        public string Es { get; set; }
    }
}
