//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppApi.App_Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class MailDelLog_T
    {
        public int Id { get; set; }
        public string UIDL { get; set; }
        public Nullable<int> MailId { get; set; }
        public Nullable<int> MailBoxId { get; set; }
        public string BoxBase { get; set; }
        public string Box { get; set; }
        public string itFrom { get; set; }
        public string Subject { get; set; }
        public Nullable<System.DateTime> RecDate { get; set; }
        public string DelUserId { get; set; }
        public string DelUserName { get; set; }
        public Nullable<System.DateTime> DelTm { get; set; }
        public string Reason { get; set; }
    }
}
