//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppApi.App_Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Menu_T
    {
        public string MenuNo { get; set; }
        public string MenuName { get; set; }
        public string MenuNameEn { get; set; }
        public Nullable<decimal> MenuOrder { get; set; }
        public Nullable<bool> MenuSub { get; set; }
        public string MenuUrl { get; set; }
        public string ParentNo { get; set; }
        public Nullable<bool> OpenWin { get; set; }
        public Nullable<int> WinWidth { get; set; }
        public Nullable<int> WinHeight { get; set; }
        public Nullable<bool> UseFlag { get; set; }
        public string FuncCode { get; set; }
        public Nullable<bool> MenuShow { get; set; }
        public string Icon { get; set; }
        public string IconUrl { get; set; }
        public Nullable<bool> IsLinkPower { get; set; }
    }
}
