//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppApi.App_Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payment_T
    {
        public int Id { get; set; }
        public string No { get; set; }
        public string Status { get; set; }
        public string Type { get; set; }
        public string MenuNo { get; set; }
        public string MenuNoNo { get; set; }
        public Nullable<decimal> PayMoney { get; set; }
        public Nullable<System.DateTime> PayDate { get; set; }
        public string Currency { get; set; }
        public string PayName { get; set; }
        public string Bank { get; set; }
        public string BankAccount { get; set; }
        public string SwiftNo { get; set; }
        public Nullable<int> IsInvoice { get; set; }
        public string InvoiceNo { get; set; }
        public Nullable<System.DateTime> InvoiceDate { get; set; }
        public string ApplyUserId { get; set; }
        public string ApplyUserName { get; set; }
        public string SpUserId { get; set; }
        public string SpUserName { get; set; }
        public Nullable<System.DateTime> SpTime { get; set; }
        public Nullable<System.DateTime> ApplyDate { get; set; }
        public string OurPayCompany { get; set; }
        public string PayBank { get; set; }
        public string PayNo { get; set; }
        public string PayBankAccount { get; set; }
        public Nullable<decimal> BankFee { get; set; }
        public Nullable<System.DateTime> TruePayDate { get; set; }
        public string PayUserId { get; set; }
        public string PayUserName { get; set; }
        public Nullable<int> Submit { get; set; }
        public string SpMsg { get; set; }
        public string Creater { get; set; }
        public string CreaterName { get; set; }
        public Nullable<System.DateTime> CreateTm { get; set; }
        public Nullable<int> SpResult { get; set; }
        public string PayCompany { get; set; }
        public string Bak { get; set; }
        public Nullable<int> OurPayCompanyId { get; set; }
    }
}
