//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppApi.App_Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pending_T
    {
        public int Id { get; set; }
        public string MenuNo { get; set; }
        public Nullable<int> Item_id { get; set; }
        public Nullable<System.DateTime> Start_date { get; set; }
        public Nullable<System.DateTime> End_date { get; set; }
        public Nullable<int> Is_repeat { get; set; }
        public Nullable<int> Is_allday { get; set; }
        public Nullable<int> ClientId { get; set; }
        public string Note { get; set; }
        public Nullable<int> Type { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<int> Urgency_level { get; set; }
        public string UrlTitle { get; set; }
        public string Url { get; set; }
        public string Creater { get; set; }
        public string CreaterName { get; set; }
        public Nullable<System.DateTime> CreateTm { get; set; }
        public Nullable<int> IsEnd { get; set; }
        public Nullable<int> Reminder { get; set; }
        public string ExId { get; set; }
        public string ExId1 { get; set; }
        public Nullable<int> Reminder_State { get; set; }
        public Nullable<System.DateTime> StartTimeEx { get; set; }
    }
}
