//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppApi.App_Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product_T
    {
        public int Id { get; set; }
        public string Guid { get; set; }
        public Nullable<int> RootId { get; set; }
        public string PRootId { get; set; }
        public string No { get; set; }
        public string CnName { get; set; }
        public string EnName { get; set; }
        public string CiqCode { get; set; }
        public string Model { get; set; }
        public string Spec { get; set; }
        public string Type { get; set; }
        public string Unit { get; set; }
        public string BeUserId { get; set; }
        public string BeUserName { get; set; }
        public string Currency { get; set; }
        public Nullable<decimal> UnitPrice { get; set; }
        public Nullable<int> MOQ { get; set; }
        public Nullable<decimal> MOQPrice { get; set; }
        public Nullable<decimal> CostPrice { get; set; }
        public string CnBak { get; set; }
        public string EnBak { get; set; }
        public string custom1 { get; set; }
        public string custom2 { get; set; }
        public string custom3 { get; set; }
        public string custom4 { get; set; }
        public string custom5 { get; set; }
        public string custom6 { get; set; }
        public string custom7 { get; set; }
        public string custom8 { get; set; }
        public string custom9 { get; set; }
        public string custom10 { get; set; }
        public string PicName { get; set; }
        public Nullable<int> PicSize { get; set; }
        public string PicType { get; set; }
        public byte[] Pic { get; set; }
        public string Creater { get; set; }
        public string CreaterName { get; set; }
        public Nullable<System.DateTime> CreateTm { get; set; }
        public string Updater { get; set; }
        public string UpdaterName { get; set; }
        public Nullable<System.DateTime> UpdateTm { get; set; }
        public string ExtentUnit { get; set; }
        public Nullable<decimal> Extent { get; set; }
        public Nullable<decimal> Width { get; set; }
        public Nullable<decimal> Height { get; set; }
        public Nullable<decimal> Volume { get; set; }
        public string WeightUnit { get; set; }
        public Nullable<decimal> NetWeight { get; set; }
        public Nullable<decimal> GrossWeight { get; set; }
        public string PackUnit { get; set; }
        public string Packing { get; set; }
        public Nullable<decimal> BoxCount { get; set; }
        public string ComIns { get; set; }
        public Nullable<decimal> AddValueTax { get; set; }
        public Nullable<decimal> DrawBack { get; set; }
        public Nullable<decimal> Count20 { get; set; }
        public Nullable<decimal> Count40 { get; set; }
        public string SName { get; set; }
    }
}
