//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppApi.App_Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductPrice_T
    {
        public int Id { get; set; }
        public Nullable<int> ProId { get; set; }
        public string Brand { get; set; }
        public string Spec { get; set; }
        public string Packing { get; set; }
        public string Currency { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<decimal> NumLow { get; set; }
        public Nullable<decimal> NumUp { get; set; }
        public Nullable<System.DateTime> ValidDate { get; set; }
        public string Updater { get; set; }
        public string UpdaterName { get; set; }
        public Nullable<System.DateTime> UpdateTime { get; set; }
        public string Bak { get; set; }
        public Nullable<int> PriId { get; set; }
    }
}
