//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppApi.App_Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Quote_T
    {
        public int Id { get; set; }
        public string No { get; set; }
        public Nullable<int> ChanceId { get; set; }
        public Nullable<int> ClientId { get; set; }
        public string ClientAddress { get; set; }
        public string ClientLinkMan { get; set; }
        public string ClientPhone { get; set; }
        public string ClinetFax { get; set; }
        public string ClientEmail { get; set; }
        public string Currency { get; set; }
        public Nullable<decimal> TotMoney { get; set; }
        public Nullable<decimal> UVR { get; set; }
        public Nullable<decimal> TotMoneyRMB { get; set; }
        public string PriceClause { get; set; }
        public string PaymentTerm { get; set; }
        public Nullable<int> ModelId { get; set; }
        public string ModelHtml { get; set; }
        public Nullable<int> Submit { get; set; }
        public Nullable<int> SpResult { get; set; }
        public string SpMsg { get; set; }
        public string SpUserId { get; set; }
        public string SpUserName { get; set; }
        public Nullable<System.DateTime> SpTime { get; set; }
        public Nullable<int> State { get; set; }
        public Nullable<System.DateTime> StateTime { get; set; }
        public string Creater { get; set; }
        public string CreaterName { get; set; }
        public Nullable<System.DateTime> CreateTm { get; set; }
        public string Updater { get; set; }
        public string UpdaterName { get; set; }
        public Nullable<System.DateTime> UpdateTm { get; set; }
        public string StateBak { get; set; }
        public Nullable<int> BranchId { get; set; }
        public string LoadPort { get; set; }
        public string AimPort { get; set; }
        public string Transport { get; set; }
        public string ArkType { get; set; }
        public Nullable<decimal> Freight { get; set; }
        public Nullable<System.DateTime> QuotationTime { get; set; }
        public string Note { get; set; }
        public string custom1 { get; set; }
        public string custom2 { get; set; }
        public string custom3 { get; set; }
        public string custom4 { get; set; }
        public string custom5 { get; set; }
        public string custom6 { get; set; }
        public string custom7 { get; set; }
        public string custom8 { get; set; }
        public string custom9 { get; set; }
        public string custom10 { get; set; }
    }
}
