//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppApi.App_Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Root_T
    {
        public int Id { get; set; }
        public Nullable<int> ParentId { get; set; }
        public string Name { get; set; }
        public string Bak { get; set; }
        public Nullable<int> IsParentSet { get; set; }
        public string AudOp { get; set; }
        public string AudUserId { get; set; }
        public Nullable<int> AudType { get; set; }
        public Nullable<int> AudTimeOut { get; set; }
        public Nullable<int> AudTimeOutAction { get; set; }
        public string Creater { get; set; }
        public string CreaterName { get; set; }
        public Nullable<System.DateTime> CreateTm { get; set; }
        public string Updater { get; set; }
        public string UpdaterName { get; set; }
        public Nullable<System.DateTime> UpdateTm { get; set; }
        public Nullable<int> Sort { get; set; }
        public Nullable<int> IsYh { get; set; }
        public string UID { get; set; }
        public string UIDType { get; set; }
        public string RoleId { get; set; }
        public string RoleType { get; set; }
    }
}
