//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppApi.App_Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Samples_T
    {
        public int Id { get; set; }
        public string No { get; set; }
        public Nullable<int> ChanceId { get; set; }
        public Nullable<int> ClientId { get; set; }
        public string ClientAddress { get; set; }
        public string ClientPostCode { get; set; }
        public string ClientLinkMan { get; set; }
        public string ClientPhone { get; set; }
        public string ClinetFax { get; set; }
        public string ClientEmail { get; set; }
        public string ClientCountry { get; set; }
        public string ClientLevel { get; set; }
        public string ClientType { get; set; }
        public string IsSf { get; set; }
        public string Payment { get; set; }
        public string Currency { get; set; }
        public Nullable<decimal> TotMoney { get; set; }
        public Nullable<decimal> UVR { get; set; }
        public Nullable<decimal> TotMoneyRMB { get; set; }
        public string Express { get; set; }
        public Nullable<decimal> ExpressMoney { get; set; }
        public Nullable<System.DateTime> RecDate { get; set; }
        public string ConNo { get; set; }
        public string IsQuote { get; set; }
        public string StockPlan { get; set; }
        public Nullable<System.DateTime> FeedbackDate { get; set; }
        public string Feedback { get; set; }
        public Nullable<int> Submit { get; set; }
        public Nullable<int> SpResult { get; set; }
        public string SpMsg { get; set; }
        public string SpUserId { get; set; }
        public string SpUserName { get; set; }
        public Nullable<System.DateTime> SpTime { get; set; }
        public Nullable<int> State { get; set; }
        public Nullable<System.DateTime> StateTime { get; set; }
        public string Creater { get; set; }
        public string CreaterName { get; set; }
        public Nullable<System.DateTime> CreateTm { get; set; }
        public string Updater { get; set; }
        public string UpdaterName { get; set; }
        public Nullable<System.DateTime> UpdateTm { get; set; }
        public string IsPass { get; set; }
        public string ExpressNo { get; set; }
    }
}
