//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppApi.App_Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class SellProduct_T
    {
        public int Id { get; set; }
        public Nullable<int> SellId { get; set; }
        public string SellNo { get; set; }
        public Nullable<long> ProductId { get; set; }
        public string No { get; set; }
        public string EnName { get; set; }
        public string CnName { get; set; }
        public string Model { get; set; }
        public string Spec { get; set; }
        public Nullable<decimal> Num { get; set; }
        public string Unit { get; set; }
        public Nullable<decimal> UnitPrice { get; set; }
        public Nullable<decimal> SellSum { get; set; }
        public string PicName { get; set; }
        public Nullable<int> PicSize { get; set; }
        public string PicType { get; set; }
        public byte[] Pic { get; set; }
        public string Bak { get; set; }
        public string Creater { get; set; }
        public string CreaterName { get; set; }
        public Nullable<System.DateTime> CreateTm { get; set; }
        public Nullable<System.Guid> GUID { get; set; }
        public string Packing { get; set; }
        public Nullable<decimal> Freight { get; set; }
        public string PackUnit { get; set; }
        public Nullable<decimal> BoxCount { get; set; }
        public Nullable<decimal> GrossWeight { get; set; }
        public Nullable<decimal> NetWeight { get; set; }
        public Nullable<decimal> Volume { get; set; }
        public Nullable<decimal> AllVolume { get; set; }
    }
}
