//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppApi.App_Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class SendSample_T
    {
        public int Id { get; set; }
        public string No { get; set; }
        public Nullable<int> ChanceId { get; set; }
        public string ChanceTitle { get; set; }
        public Nullable<int> ClientId { get; set; }
        public string CientName { get; set; }
        public string ClientAddress { get; set; }
        public string ClientLinkMan { get; set; }
        public string ClientPhone { get; set; }
        public string ClinetFax { get; set; }
        public string ClientEmail { get; set; }
    }
}
