//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppApi.App_Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Shipment_T
    {
        public int Id { get; set; }
        public Nullable<int> SellId { get; set; }
        public string SellNo { get; set; }
        public Nullable<System.DateTime> DeliveryDate { get; set; }
        public Nullable<int> ClientId { get; set; }
        public string ClientName { get; set; }
        public string Currency { get; set; }
        public Nullable<decimal> UVR { get; set; }
        public string PriceClause { get; set; }
        public string Settlement { get; set; }
        public string OurCompany { get; set; }
        public string ExSaleUserId { get; set; }
        public string ExSaleUserName { get; set; }
        public string Merchandiser { get; set; }
        public string MerchandiserName { get; set; }
        public Nullable<System.DateTime> ShipmentDate { get; set; }
        public string State { get; set; }
        public Nullable<decimal> RecDeposit { get; set; }
        public Nullable<System.DateTime> DepositDate { get; set; }
        public Nullable<decimal> RecBalance { get; set; }
        public Nullable<System.DateTime> BalanceDate { get; set; }
        public Nullable<decimal> AdvanceRate { get; set; }
        public string TradeStyle { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public string FreightState { get; set; }
        public Nullable<int> SpResult { get; set; }
        public Nullable<System.DateTime> SpTime { get; set; }
        public Nullable<int> ProCount { get; set; }
        public string ClientLevel { get; set; }
        public Nullable<System.DateTime> StockStartDate { get; set; }
        public string LoadPort { get; set; }
        public string AimPort { get; set; }
        public string TransPortCompany { get; set; }
        public Nullable<System.DateTime> ShippingDate { get; set; }
        public string SeaCurrency { get; set; }
        public string Voyage { get; set; }
        public string TransPort { get; set; }
        public string Batches { get; set; }
        public string Transfer { get; set; }
        public string BoxPile { get; set; }
        public Nullable<decimal> AllVolume { get; set; }
        public Nullable<System.DateTime> BookingDate { get; set; }
        public Nullable<System.DateTime> PreDeliveryDate { get; set; }
        public Nullable<decimal> ShippingPrice { get; set; }
        public Nullable<System.DateTime> OrderDate { get; set; }
        public string LoadingDetail { get; set; }
        public string Consignee { get; set; }
        public string Notifier { get; set; }
        public string Mark { get; set; }
        public string DocRequire { get; set; }
        public string SpeRequire { get; set; }
        public string TestRequire { get; set; }
        public string SpecifyForward { get; set; }
        public string BusinessConfirm { get; set; }
        public string ReplaceGoods { get; set; }
        public string CIQ { get; set; }
        public string PlayJoe { get; set; }
        public string MarkRequire { get; set; }
        public string PackingRequire { get; set; }
        public Nullable<decimal> TotalValue { get; set; }
        public Nullable<decimal> TotalNum { get; set; }
        public Nullable<decimal> TotalCase { get; set; }
        public Nullable<decimal> TotalSuttle { get; set; }
        public Nullable<decimal> ShippingNum { get; set; }
        public Nullable<decimal> OrderSize { get; set; }
        public string Bak { get; set; }
        public string custom1 { get; set; }
        public string custom2 { get; set; }
        public string custom3 { get; set; }
        public string custom4 { get; set; }
        public string custom5 { get; set; }
        public string custom6 { get; set; }
        public string custom7 { get; set; }
        public string custom8 { get; set; }
        public string custom9 { get; set; }
        public string custom10 { get; set; }
        public string Creater { get; set; }
        public string CreaterName { get; set; }
        public Nullable<System.DateTime> CreateTm { get; set; }
        public string SpUserId { get; set; }
        public Nullable<int> Submit { get; set; }
        public string SpMsg { get; set; }
        public string SpUserName { get; set; }
        public string No { get; set; }
        public Nullable<int> CompanyId { get; set; }
        public string CompanyName { get; set; }
        public string ClientAdress { get; set; }
        public string ClientPhone { get; set; }
        public string ClientEmail { get; set; }
        public string ClientCountry { get; set; }
        public string PriceClauseText { get; set; }
        public string SettlementText { get; set; }
        public Nullable<System.DateTime> PreArriveDate { get; set; }
        public Nullable<System.DateTime> TrueDeliveryDate { get; set; }
        public string CancelNo { get; set; }
        public string AllProName { get; set; }
        public string ShippingCompany { get; set; }
        public string ShippingName { get; set; }
        public string ShippingPhone { get; set; }
        public string VoyageNum { get; set; }
        public string ContainerNo { get; set; }
        public string BoxCount { get; set; }
        public string BlNo { get; set; }
        public Nullable<System.DateTime> ShipDate { get; set; }
        public Nullable<System.DateTime> SailDate { get; set; }
        public Nullable<System.DateTime> CyDate { get; set; }
        public Nullable<System.DateTime> CysDate { get; set; }
        public Nullable<decimal> TotalValueRMB { get; set; }
        public string DeclareValue { get; set; }
        public string PortSurchange { get; set; }
        public string Premium { get; set; }
        public string OceanFee { get; set; }
        public string Commission { get; set; }
        public string BankFee { get; set; }
        public string ModelFee { get; set; }
        public string SideMark { get; set; }
        public string MidPort { get; set; }
    }
}
