//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppApi.App_Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class SysDictionaryClass_T
    {
        public int Id { get; set; }
        public string DataClass { get; set; }
        public string DataType { get; set; }
        public Nullable<bool> UseValue1 { get; set; }
        public Nullable<bool> UseValue2 { get; set; }
        public Nullable<bool> UseValue3 { get; set; }
        public Nullable<bool> UseValue4 { get; set; }
        public Nullable<bool> UseValue5 { get; set; }
        public Nullable<int> BigSort { get; set; }
        public Nullable<int> Sort { get; set; }
        public Nullable<bool> ShowFlag { get; set; }
        public string Bak { get; set; }
        public Nullable<int> IsRead { get; set; }
    }
}
