//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppApi.App_Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TCRMDOCEntities : DbContext
    {
        public TCRMDOCEntities()
            : base("name=TCRMDOCEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<File_T> File_T { get; set; }
        public DbSet<FileAud_T> FileAud_T { get; set; }
        public DbSet<FileAudLog_T> FileAudLog_T { get; set; }
        public DbSet<FileEx_T> FileEx_T { get; set; }
        public DbSet<FileLog_T> FileLog_T { get; set; }
        public DbSet<FilePower_T> FilePower_T { get; set; }
        public DbSet<FileServer_T> FileServer_T { get; set; }
        public DbSet<FileShor_T> FileShor_T { get; set; }
        public DbSet<FileTrash_T> FileTrash_T { get; set; }
        public DbSet<FileType_T> FileType_T { get; set; }
        public DbSet<RoleSecurity_T> RoleSecurity_T { get; set; }
        public DbSet<Root_T> Root_T { get; set; }
        public DbSet<RootPower_T> RootPower_T { get; set; }
        public DbSet<Security_T> Security_T { get; set; }
        public DbSet<SynRoot_T> SynRoot_T { get; set; }
        public DbSet<SynTime_T> SynTime_T { get; set; }
        public DbSet<Tag_T> Tag_T { get; set; }
        public DbSet<TagClass_T> TagClass_T { get; set; }
        public DbSet<TagRoot_T> TagRoot_T { get; set; }
        public DbSet<TempPower_T> TempPower_T { get; set; }
        public DbSet<UploadTemp_T> UploadTemp_T { get; set; }
        public DbSet<UserRoot_T> UserRoot_T { get; set; }
    }
}
