//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppApi.App_Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TempImg_T
    {
        public int Id { get; set; }
        public byte[] imgdata { get; set; }
        public string FileName { get; set; }
        public Nullable<int> FileSize { get; set; }
        public string FileType { get; set; }
        public Nullable<System.DateTime> CreateTm { get; set; }
        public Nullable<short> IsHtml { get; set; }
    }
}
