//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppApi.App_Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TestQuestions_T
    {
        public int Id { get; set; }
        public Nullable<int> KnowledgeId { get; set; }
        public string KnowledgeTitle { get; set; }
        public Nullable<int> TestPaperId { get; set; }
        public Nullable<int> Rank { get; set; }
    }
}
