//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppApi.App_Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class UploadTemp_T
    {
        public long Id { get; set; }
        public Nullable<int> RootId { get; set; }
        public string Type { get; set; }
        public string Security { get; set; }
        public string Bak { get; set; }
        public string Reason { get; set; }
        public string Creater { get; set; }
        public string CreaterName { get; set; }
        public Nullable<System.DateTime> CreateTm { get; set; }
        public Nullable<int> DeptId { get; set; }
        public string DeptName { get; set; }
        public Nullable<int> IsAud { get; set; }
        public string ConNo { get; set; }
        public string TagClass { get; set; }
        public string Tag { get; set; }
        public string TagId { get; set; }
    }
}
