//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppApi.App_Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class User_T
    {
        public int UID { get; set; }
        public string UserId { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public string CodeHead { get; set; }
        public Nullable<int> BranchId { get; set; }
        public Nullable<int> DeptId { get; set; }
        public string Sex { get; set; }
        public string Mobile { get; set; }
        public string Phone { get; set; }
        public string Email { get; set; }
        public string Duty { get; set; }
        public string State { get; set; }
        public Nullable<int> LogErr { get; set; }
        public Nullable<int> Sort { get; set; }
        public Nullable<System.DateTime> OnlineTime { get; set; }
        public string Guid { get; set; }
        public string LoginIp { get; set; }
        public Nullable<System.DateTime> LoginTime { get; set; }
        public string Creater { get; set; }
        public string CreaterName { get; set; }
        public Nullable<System.DateTime> Createtm { get; set; }
        public string Updater { get; set; }
        public string UpdaterName { get; set; }
        public Nullable<System.DateTime> UpdateTm { get; set; }
        public byte[] Img { get; set; }
        public Nullable<int> UserType { get; set; }
        public string PicName { get; set; }
        public string PicType { get; set; }
        public Nullable<int> PicSize { get; set; }
        public byte[] PicData { get; set; }
        public string appid { get; set; }
        public string Hxid { get; set; }
        public string X3UserId { get; set; }
    }
}
