//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppApi.App_Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class WarningConfig_T
    {
        public int Id { get; set; }
        public string MenuNo { get; set; }
        public Nullable<int> Warning_type { get; set; }
        public string Value { get; set; }
        public string Field { get; set; }
        public string Text { get; set; }
        public string Text_en { get; set; }
        public string Type { get; set; }
        public string Para { get; set; }
        public string TableName { get; set; }
        public Nullable<int> Sort { get; set; }
    }
}
