//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppApi.App_Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Provider_T
    {
        public int Id { get; set; }
        public string No { get; set; }
        public string Name { get; set; }
        public string Phone { get; set; }
        public string Email { get; set; }
        public string Fax { get; set; }
        public string Web { get; set; }
        public string Address { get; set; }
        public string BankName { get; set; }
        public string BankUser { get; set; }
        public string BankAccounts { get; set; }
        public string TaxNumber { get; set; }
        public string Level { get; set; }
        public string Type { get; set; }
        public string Source { get; set; }
        public string Bak { get; set; }
        public string SendLinkMan { get; set; }
        public string SendLinkManTel { get; set; }
        public string SendLinkManMobile { get; set; }
        public string BeUserId { get; set; }
        public string BeUserName { get; set; }
        public string Creater { get; set; }
        public string CreaterName { get; set; }
        public Nullable<System.DateTime> CreateTm { get; set; }
        public string Updater { get; set; }
        public string UpdaterName { get; set; }
        public Nullable<System.DateTime> UpdateTm { get; set; }
        public string Name_EN { get; set; }
        public string Province { get; set; }
        public string City { get; set; }
        public string Payment { get; set; }
        public Nullable<decimal> Tariff { get; set; }
        public string Email_LogisticsContact { get; set; }
        public string SendLinkManQQ { get; set; }
        public string SendLinkManSex { get; set; }
        public string custom1 { get; set; }
        public string custom2 { get; set; }
        public string custom3 { get; set; }
        public string custom4 { get; set; }
        public string custom5 { get; set; }
        public string custom6 { get; set; }
        public string custom7 { get; set; }
        public string custom8 { get; set; }
        public string custom9 { get; set; }
        public string custom10 { get; set; }
    }
}
