//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppApi.App_Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClientFollow_V
    {
        public string ClientName { get; set; }
        public int Expr1 { get; set; }
        public Nullable<int> Expr2 { get; set; }
        public Nullable<int> Expr3 { get; set; }
        public Nullable<System.DateTime> Expr4 { get; set; }
        public string Expr5 { get; set; }
        public string Expr6 { get; set; }
        public Nullable<int> Expr7 { get; set; }
        public string Expr8 { get; set; }
        public string Expr9 { get; set; }
        public Nullable<System.DateTime> Expr10 { get; set; }
        public string Expr11 { get; set; }
        public string Expr12 { get; set; }
        public Nullable<System.DateTime> Expr13 { get; set; }
        public int Id { get; set; }
        public Nullable<int> ClientId { get; set; }
        public Nullable<int> ChanceId { get; set; }
        public Nullable<System.DateTime> FollwTime { get; set; }
        public string AddName { get; set; }
        public string Type { get; set; }
        public string Title { get; set; }
        public string Info { get; set; }
        public Nullable<int> MailId { get; set; }
        public string Creater { get; set; }
        public string CreaterName { get; set; }
        public Nullable<System.DateTime> CreateTm { get; set; }
        public string Updater { get; set; }
        public string UpdaterName { get; set; }
        public Nullable<System.DateTime> UpdateTm { get; set; }
    }
}
