//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppApi.App_Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class MailBox_T
    {
        public int Id { get; set; }
        public Nullable<int> BranchId { get; set; }
        public string Name { get; set; }
        public string Sign { get; set; }
        public string Email { get; set; }
        public string Smtp { get; set; }
        public string SmtpVerify { get; set; }
        public Nullable<int> SmtpPort { get; set; }
        public string IsVerify { get; set; }
        public string Pop { get; set; }
        public string PopVerify { get; set; }
        public Nullable<int> PopPort { get; set; }
        public Nullable<int> IsAli { get; set; }
        public string UserName { get; set; }
        public string Pass { get; set; }
        public Nullable<int> SmtpCustom { get; set; }
        public string SmtpUser { get; set; }
        public string SmtpPass { get; set; }
        public string IsBak { get; set; }
        public Nullable<int> BakDay { get; set; }
        public Nullable<int> Sort { get; set; }
        public Nullable<int> Mode { get; set; }
        public Nullable<int> AutoRec { get; set; }
        public Nullable<int> Random { get; set; }
        public Nullable<int> AddSaleName { get; set; }
        public Nullable<int> Inside { get; set; }
        public Nullable<int> Receipt { get; set; }
        public Nullable<int> ReadMode { get; set; }
        public string SaveBase { get; set; }
        public Nullable<int> SaveBaseDay { get; set; }
        public string Creater { get; set; }
        public string CreaterName { get; set; }
        public Nullable<System.DateTime> CreateTm { get; set; }
        public string Updater { get; set; }
        public string UpdaterName { get; set; }
        public Nullable<System.DateTime> UpdateTm { get; set; }
        public Nullable<int> AutoRecPl { get; set; }
        public Nullable<System.DateTime> AutoRecTime { get; set; }
        public Nullable<int> RemoteTrack { get; set; }
        public string AutoCc { get; set; }
        public string AutoBcc { get; set; }
        public Nullable<int> IsNewMag { get; set; }
    }
}
