//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppApi.App_Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class DocFolder_T
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Creater { get; set; }
        public int IsSys { get; set; }
        public int ParentId { get; set; }
        public int Sort { get; set; }
        public System.DateTime CreateTm { get; set; }
        public string Shared { get; set; }
        public string SharedUser { get; set; }
    }
}
