//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppApi.App_Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomsClient_T
    {
        public int Id { get; set; }
        public string BNo { get; set; }
        public string shujuyuan { get; set; }
        public string jinchukou { get; set; }
        public Nullable<System.DateTime> riqi { get; set; }
        public string guonei { get; set; }
        public string guowai { get; set; }
        public string hscode { get; set; }
        public string shangpinmiaoshu { get; set; }
        public Nullable<decimal> zhongliang { get; set; }
        public Nullable<decimal> jine { get; set; }
        public string yuanchanguo { get; set; }
        public string guanqu { get; set; }
        public string bianhao { get; set; }
        public string Creater { get; set; }
        public string CreaterName { get; set; }
        public Nullable<System.DateTime> CreateTm { get; set; }
    }
}
