//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppApi.App_Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class EdmTaskAddress_T
    {
        public long Id { get; set; }
        public Nullable<int> TaskId { get; set; }
        public string FromEmail { get; set; }
        public string ServerNo { get; set; }
        public string ClientNo { get; set; }
        public Nullable<int> ClientId { get; set; }
        public Nullable<int> ClientAddId { get; set; }
        public string Email { get; set; }
        public string Name { get; set; }
        public string CompanyName { get; set; }
        public string Country { get; set; }
        public string Province { get; set; }
        public string City { get; set; }
        public string Tel { get; set; }
        public string Bak { get; set; }
        public Nullable<System.DateTime> SendTime { get; set; }
        public string Result { get; set; }
        public string FailureMsg { get; set; }
        public Nullable<System.DateTime> OpenTime { get; set; }
        public string OpenIp { get; set; }
        public string OpenArea { get; set; }
        public Nullable<System.DateTime> OpenNowTime { get; set; }
        public Nullable<int> OpenCount { get; set; }
        public string DnsResult { get; set; }
        public string DnsFailureMsg { get; set; }
        public string SmtpResult { get; set; }
        public string SmtpFailureMsg { get; set; }
        public Nullable<System.DateTime> CreateTm { get; set; }
        public string UserId { get; set; }
        public string GroupName { get; set; }
    }
}
