//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppApi.App_Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class SysDictionary_T
    {
        public int Id { get; set; }
        public string DataClass { get; set; }
        public string DataType { get; set; }
        public string DataText { get; set; }
        public string DataValue1 { get; set; }
        public string DataValue2 { get; set; }
        public string DataValue3 { get; set; }
        public string DataValue4 { get; set; }
        public string DataValue5 { get; set; }
        public Nullable<int> Sort { get; set; }
        public string Creater { get; set; }
        public string CreaterName { get; set; }
        public Nullable<System.DateTime> CreateTm { get; set; }
        public string Updater { get; set; }
        public string UpdaterName { get; set; }
        public Nullable<System.DateTime> UpdateTm { get; set; }
    }
}
