//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppApi.App_Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mail_T
    {
        public int Id { get; set; }
        public Nullable<System.Guid> guid { get; set; }
        public Nullable<int> MailBoxId { get; set; }
        public Nullable<int> ReadMode { get; set; }
        public string UIDL { get; set; }
        public Nullable<int> Inside { get; set; }
        public string FromName { get; set; }
        public string FromEmail { get; set; }
        public string Subject { get; set; }
        public string SendDate { get; set; }
        public string MailType { get; set; }
        public string itFrom { get; set; }
        public string itTo { get; set; }
        public string cc { get; set; }
        public string bcc { get; set; }
        public string TextBody { get; set; }
        public string HtmlBody { get; set; }
        public string ReplyTo { get; set; }
        public string Read { get; set; }
        public string ReadUID { get; set; }
        public string BoxBase { get; set; }
        public string Box { get; set; }
        public Nullable<int> RootId { get; set; }
        public Nullable<System.DateTime> RecDate { get; set; }
        public string priority { get; set; }
        public string RE { get; set; }
        public string Notification { get; set; }
        public string notify { get; set; }
        public string star { get; set; }
        public string redflag { get; set; }
        public string UID { get; set; }
        public Nullable<int> ischeck { get; set; }
        public string checkmsg { get; set; }
        public string SPUserId { get; set; }
        public string SPUserName { get; set; }
        public Nullable<System.DateTime> SPTime { get; set; }
        public Nullable<int> SUID { get; set; }
        public string IP { get; set; }
        public string Area { get; set; }
        public string Bak { get; set; }
        public string BaseDb { get; set; }
        public Nullable<long> BaseId { get; set; }
        public string MailDate { get; set; }
        public string RevUserId { get; set; }
        public string RevUserName { get; set; }
        public Nullable<int> MailSize { get; set; }
        public Nullable<short> AccCount { get; set; }
        public string REALFROM { get; set; }
        public string ReturnPath { get; set; }
        public string MailLabel { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public string ConType { get; set; }
        public Nullable<int> Type { get; set; }
        public Nullable<int> RFMailId { get; set; }
        public Nullable<int> LocalTrack { get; set; }
        public Nullable<int> RemoteTrack { get; set; }
        public Nullable<int> IsReceipt { get; set; }
        public Nullable<int> ModId { get; set; }
        public Nullable<System.DateTime> TopTime { get; set; }
        public Nullable<System.DateTime> RemindTime { get; set; }
        public Nullable<System.DateTime> PfDate { get; set; }
        public Nullable<int> IsDeal { get; set; }
        public Nullable<int> CommCount { get; set; }
        public string CommReadUID { get; set; }
        public Nullable<int> ChanceId { get; set; }
        public Nullable<System.DateTime> OpenTime { get; set; }
        public string OpenIp { get; set; }
        public string OpenArea { get; set; }
        public Nullable<System.DateTime> OpenNowTime { get; set; }
        public Nullable<int> OpenCount { get; set; }
        public Nullable<int> FromUID { get; set; }
        public Nullable<int> FromBoxId { get; set; }
        public Nullable<int> FromMailId { get; set; }
        public string FromRE { get; set; }
        public Nullable<System.DateTime> JzMailTm { get; set; }
        public Nullable<int> JzMailBoxId { get; set; }
        public string JzBox { get; set; }
        public Nullable<int> JzRootId { get; set; }
        public Nullable<int> FileStoreId { get; set; }
        public string FileKey { get; set; }
        public Nullable<int> GdClientId { get; set; }
        public string FileRoot { get; set; }
        public string FileStore { get; set; }
        public string FileZip { get; set; }
    }
}
