//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppApi.App_Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Doc_T
    {
        public int Id { get; set; }
        public string Type { get; set; }
        public string Name { get; set; }
        public long Size { get; set; }
        public string Keywords { get; set; }
        public int Labelid { get; set; }
        public string Bak { get; set; }
        public string Creater { get; set; }
        public System.DateTime CreateTime { get; set; }
        public Nullable<System.DateTime> UpdateTime { get; set; }
        public int State { get; set; }
        public int FolderId { get; set; }
        public int IsDel { get; set; }
        public string Shared { get; set; }
        public string SharedUser { get; set; }
        public int DownloadCount { get; set; }
        public int DataId { get; set; }
    }
}
