//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppApi.App_Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class MailInq_T
    {
        public int MailId { get; set; }
        public Nullable<int> Inq { get; set; }
        public Nullable<int> InqMailIdBase { get; set; }
        public Nullable<int> InqReLimit { get; set; }
        public string InqBak { get; set; }
        public Nullable<int> InqYfp { get; set; }
        public Nullable<System.DateTime> InqReTime { get; set; }
        public string InqSaleUserId { get; set; }
        public string InqSaleUserName { get; set; }
        public string InqDevUserId { get; set; }
        public string InqDevUserName { get; set; }
        public Nullable<int> InqClientId { get; set; }
        public string InqClientName { get; set; }
        public Nullable<int> InqLinkManId { get; set; }
        public string InqLinkMan { get; set; }
        public string InqLinkManEmail { get; set; }
        public string InqLinkManMobile { get; set; }
        public string InqLinkManTel { get; set; }
        public Nullable<System.DateTime> InqFpTime { get; set; }
        public string InqFpUserId { get; set; }
        public string InqFpUserName { get; set; }
        public string InqProId { get; set; }
        public string InqProName { get; set; }
        public string InqWeb { get; set; }
        public string InqSource { get; set; }
        public string InqClientClass { get; set; }
        public string InqCountry { get; set; }
        public Nullable<int> InqIsOld { get; set; }
        public string InqLinkManEmail1 { get; set; }
        public string InqLinkManEmail2 { get; set; }
    }
}
